language: go

go:
  - 1.12.x
  - tip

git:
  depth: 1

services:
  - postgresql

before_install:
  - go get -t -v ./...

install:
  - go get github.com/gorilla/mux
  - go get github.com/jinzhu/gorm
  - go get github.com/joho/godotenv

notifications:
  email: false

before_script:
  - psql -c 'create database rest_db;' -U postgres

script:
  - go test -v -coverprofile=coverage.out -covermode=atomic
  - go tool cover -html=coverage.out -o coverage.html 

after_success:
  - bash <(curl -s https://codecov.io/bash)