language: go

go:
  - 1.12.5
  - tip

services:
  - postgresql

before_install:
  - go get -t -v ./...

install:
  - go get github.com/gorilla/mux
  - go get github.com/jinzhu/gorm
  - go get github.com/joho/godotenv

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go tool cover -html=coverage.out -o coverage.html 

after_success:
  - bash <(curl -s https://codecov.io/bash)