language: go

go:
  - 1.12.5
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.out -covermode=atomic
  - go tool cover -html=coverage.out -o coverage.html 

after_success:
  - bash <(curl -s https://codecov.io/bash)